/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import desenhos.Figura2D;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.ArrayList;
import java.util.Iterator;

/**
 * Classe utilizada para definir a tela de desenho e como será pintada.
 *
 * @author Rodrigo dos Santos Pequeno - 201600114780
 */
public class Tela extends javax.swing.JPanel {

    private ArrayList<Figura2D> figurasDesenhadas;

    /**
     * Cria um novo form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * Método utilizado para atualizar o ArrayList de figuras.
     *
     * @param figurasDesenhadas ArrayList de figuras que será exibido na tela.
     */
    public void setFigurasDesenhadas(ArrayList<Figura2D> figurasDesenhadas) {
        this.figurasDesenhadas = figurasDesenhadas;
    }

    /**
     * Método usado para pintar na tela todas as figuras.
     *
     * @param g
     */
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        Graphics2D draw = (Graphics2D) g;
        draw.setColor(Color.WHITE);
        draw.fillRect(0, 0, this.getWidth(), this.getHeight());

        for (Iterator<Figura2D> it = figurasDesenhadas.iterator(); it.hasNext();) {
            Figura2D figurasDesenhada = it.next();
            figurasDesenhada.desenharFigura(g);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
